### ISSUE TITLE
most buildings are located at null island?

### ISSUE THREAD

**Issue by henriterhofte** [energietransitie/needforheat-server-api#112]
It seems (almost) all buildings are located at the infamous Null Island.
See also: https://www.youtube.com/watch?v=bjvIpI-1w84 
If there is no location given, please do NOT use 0 for latitude and longitude (als is IS an valid location on earth), use a proper way to indicate there is NO information on the location.

Perhaps use:
```
	// Set the latitude and longitude values to NULL
	latitude := sql.NullFloat64{Valid: false}
	longitude := sql.NullFloat64{Valid: false}
``` 
|id |created_at             |updated_at             |deleted_at|account_id|longtitude  |latitude   |tz_name         |
|---|-----------------------|-----------------------|----------|----------|------------|-----------|----------------|
|60 |2023-06-01 09:28:38.681|2023-06-01 09:28:38.681|          |64        |0           |0          |                |
|59 |2023-06-01 09:24:34.435|2023-06-01 09:24:34.435|          |66        |0           |0          |                |
|58 |2023-06-01 08:14:25.195|2023-06-01 08:14:25.195|          |65        |0           |0          |                |
|57 |2023-05-31 09:56:15.197|2023-05-31 09:56:15.197|          |62        |0           |0          |                |
|56 |2023-05-31 09:22:18.258|2023-05-31 09:22:18.258|          |61        |0           |0          |                |
|55 |2023-05-31 09:20:38.019|2023-05-31 09:20:38.019|          |60        |0           |0          |                |
|54 |2023-05-31 09:10:20.234|2023-05-31 09:10:20.234|          |59        |0           |0          |                |
|53 |2023-05-31 09:08:05.861|2023-05-31 09:08:05.861|          |58        |0           |0          |                |
|52 |2023-05-31 08:54:24.629|2023-05-31 08:54:24.629|          |57        |0           |0          |                |
|51 |2023-05-31 08:50:45.050|2023-05-31 08:50:45.050|          |56        |0           |0          |                |
|50 |2023-05-30 15:13:11.568|2023-05-30 15:13:11.568|          |55        |0           |0          |                |
|49 |2023-05-30 15:08:29.213|2023-05-30 15:08:29.213|          |54        |0           |0          |                |
|48 |2023-05-30 15:02:48.363|2023-05-30 15:02:48.363|          |53        |0           |0          |                |
|47 |2023-05-30 15:01:42.981|2023-05-30 15:01:42.981|          |52        |0           |0          |                |
|46 |2023-05-30 14:59:03.503|2023-05-30 14:59:03.503|          |51        |0           |0          |                |
|45 |2023-05-30 14:58:23.615|2023-05-30 14:58:23.615|          |50        |0           |0          |                |
|44 |2023-05-30 14:57:38.102|2023-05-30 14:57:38.102|          |49        |0           |0          |                |
|43 |2023-05-30 13:00:08.664|2023-05-30 13:00:08.664|          |47        |0           |0          |                |
|42 |2023-05-30 12:50:00.553|2023-05-30 12:50:00.553|          |48        |0           |0          |                |
|41 |2023-05-30 09:40:44.106|2023-05-30 09:40:44.106|          |46        |0           |0          |                |
|40 |2023-05-26 08:19:46.960|2023-05-26 08:19:46.960|          |45        |0           |0          |                |
|39 |2023-05-24 12:12:31.958|2023-05-24 12:12:31.958|          |44        |0           |0          |                |
|38 |2023-05-24 09:48:36.836|2023-05-24 09:48:36.836|          |43        |0           |0          |                |
|37 |2023-05-23 13:34:47.868|2023-05-23 13:34:47.868|          |42        |0           |0          |                |
|36 |2023-05-23 12:14:30.756|2023-05-23 12:14:30.756|          |39        |0           |0          |                |
|35 |2023-05-23 12:05:14.622|2023-05-23 12:05:14.622|          |41        |0           |0          |                |
|34 |2023-05-23 10:06:51.952|2023-05-23 10:06:51.952|          |40        |0           |0          |                |
|33 |2023-05-22 17:11:46.447|2023-05-22 17:11:46.447|          |37        |0           |0          |                |
|32 |2023-05-22 15:53:24.865|2023-05-22 15:53:24.865|          |1         |0           |0          |                |
|29 |2023-05-22 13:10:41.897|2023-05-22 13:10:41.897|          |1         |0           |0          |                |
|28 |2023-05-18 10:58:42.078|2023-05-18 10:58:42.078|          |36        |0           |0          |                |
|27 |2023-05-18 10:43:58.246|2023-05-18 10:43:58.246|          |35        |0           |0          |                |
|26 |2023-05-17 14:29:03.917|2023-05-17 14:29:03.917|          |34        |0           |0          |                |
|25 |2023-05-11 07:57:23.911|2023-05-11 07:57:23.911|          |10        |0           |0          |                |
|23 |2023-05-16 12:35:26.473|2023-05-16 12:35:26.473|          |32        |0           |0          |                |
|22 |2023-05-16 08:04:07.563|2023-05-16 08:04:07.563|          |30        |0           |0          |                |
|21 |2023-05-16 07:52:32.321|2023-05-16 07:52:32.321|          |29        |0           |0          |                |
|20 |2023-05-16 07:30:06.217|2023-05-16 07:30:06.217|          |28        |0           |0          |                |
|19 |2023-05-13 11:25:27.992|2023-05-13 11:25:27.992|          |25        |0           |0          |                |
|18 |2023-05-13 09:51:12.347|2023-05-13 09:51:12.347|          |24        |0           |0          |                |
|17 |2023-05-12 14:03:54.242|2023-05-12 14:03:54.242|          |23        |0           |0          |                |
|16 |2023-05-12 13:45:31.675|2023-05-12 13:45:31.675|          |22        |0           |0          |                |
|15 |2023-05-12 11:33:31.164|2023-05-12 11:33:31.164|          |22        |0           |0          |                |
|14 |2023-05-12 08:37:29.428|2023-05-12 08:37:29.428|          |21        |0           |0          |                |
|13 |2023-05-12 08:22:47.413|2023-05-12 08:22:47.413|          |20        |0           |0          |                |
|12 |2023-05-12 07:56:26.553|2023-05-12 07:56:26.553|          |19        |0           |0          |                |
|11 |2023-05-11 12:43:18.390|2023-05-11 12:43:18.390|          |14        |0           |0          |                |
|10 |2023-05-11 11:31:20.741|2023-05-11 11:31:20.741|          |13        |0           |0          |                |
|9  |2023-05-11 07:57:23.911|2023-05-11 07:57:23.911|          |10        |0           |0          |                |
|8  |2023-05-10 17:45:45.068|2023-05-10 17:45:45.068|          |9         |0           |0          |                |
|7  |2023-05-10 08:48:21.533|2023-05-10 08:48:21.533|          |8         |0           |0          |                |
|6  |2023-05-10 08:31:17.695|2023-05-10 08:31:17.695|          |7         |0           |0          |                |
|5  |2023-05-10 08:29:37.909|2023-05-10 08:29:37.909|          |6         |0           |0          |                |
|4  |2023-05-10 08:29:09.757|2023-05-10 08:29:09.757|          |5         |0           |0          |                |
|3  |2023-05-10 08:21:53.693|2023-05-10 08:21:53.693|          |4         |0           |0          |                |
|2  |2023-05-09 13:21:06.397|2023-05-09 13:21:06.397|          |3         |0           |0          |                |
|1  |2023-04-20 11:13:05.566|2023-04-20 11:13:05.566|          |2         |1.1233999729|6.678899765|Europe/Amsterdam|

**Comment by Labhatorian** [comment]
Closing as it's now handled by the energy query which should fix this issue
